data_mix:
  (): dataset_construction.DataMix
  name: "pretraining_testing"
  shuffle: false
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: true
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  datasets:
# Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: cerebras/SlimPajama-627B
      train_split: "train[:5%]"
      test_split: "test"
      build_test_set_from_train: false
      num_train_examples:  1000
      num_test_examples: 1000

tokenizer: "mistralai/Mistral-7B-v0.1"
