data_mix:
  (): dataset_construction.DataMix
  name: "pretraining_testing"
  shuffle: false
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: true
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  datasets:
    - (): dataset_construction.DatasetConfig
      dataset_path: manu/opus100-en-fr
      train_split: "train"
      test_split: "test"
      build_test_set_from_train: false
      num_train_examples:  1000
      num_test_examples: 1000
    - (): dataset_construction.DatasetConfig
      dataset_path: manu/french_librispeech_text_only
      train_split: "train"
      build_test_set_from_train: true
      num_test_examples: 1000
    - (): dataset_construction.DatasetConfig
      dataset_path: manu/french_podcasts
      train_split: "train"
      build_test_set_from_train: true
      num_test_examples: 1000
      filtering_function:
        (): dataset_collection.french.french_transcribed_podcast.Filter
      preprocessing_function:
        (): dataset_collection.french.french_transcribed_podcast.Mapper
