data_mix:
  (): dataset_construction.DataMix
  name: "english_30b"
  shuffle: false
  # local_save_dir: data/ # Do not save this one
  load_from_local_save_dir: false
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: true
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  datasets:
# Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: cerebras/SlimPajama-627B
      train_split: "train"
      test_split: "test"
      build_test_set_from_train: false
      dataset_kwargs:
        data_dir: train/chunk1

tokenizer: "mistralai/Mistral-7B-v0.1"
