data_mix:
  (): dataset_construction.DataMix
  name: "english_627B"
  shuffle: false
  load_from_local_save_dir: false
  local_save_dir: data
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: false
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  max_shard_size: "2GB"
  datasets:
# Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train"
      test_split: "test"
      build_test_set_from_train: false # but hacky af
      preprocessing_function:
        (): dataset_collection.english.gutenberg_canaries.GutenbergFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: manu/gutenberg_canaries
      train_split: "train"
      build_test_set_from_train: true
      num_test_examples: 0
      preprocessing_function:
        (): dataset_collection.english.gutenberg_canaries.GutenbergMapper

# tokenizer: "mistralai/Mistral-7B-v0.1"
tokenizer: "manu/tok-fr-en-code"
