data_mix:
  (): dataset_construction.DataMix
  name: "english_627B"
  shuffle: false
  load_from_local_save_dir: false
  local_save_dir: /gpfsscratch/rech/qts/ucg53vj/croissant_data
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: false
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  max_shard_size: "5GB"
  datasets:
# Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train"
      test_split: "test"
      build_test_set_from_train: false
      load_from_disk: true
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/gutenberg_canaries
      train_split: "train"
      build_test_set_from_train: true
      num_test_examples: 0

# tokenizer: "mistralai/Mistral-7B-v0.1"
tokenizer: "/gpfsstore/rech/qts/ucg53vj/tok-fr-en-code"
