data_mix:
  (): dataset_construction.DataMix
  name: "english_627B"
  shuffle: false
  load_from_local_save_dir: false
  local_save_dir: /gpfsscratch/rech/qts/ucg53vj/croissant_data
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: false
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  max_shard_size: "5GB"
  datasets:
# Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[0%:5%]"
      test_split: "test[0%:5%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[5%:10%]"
      test_split: "test[5%:10%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[10%:15%]"
      test_split: "test[10%:15%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[15%:20%]"
      test_split: "test[15%:20%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[20%:25%]"
      test_split: "test[20%:25%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[25%:30%]"
      test_split: "test[25%:30%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[30%:35%]"
      test_split: "test[30%:35%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[35%:40%]"
      test_split: "test[35%:40%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[40%:45%]"
      test_split: "test[40%:45%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[45%:50%]"
      test_split: "test[45%:50%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[50%:55%]"
      test_split: "test[50%:55%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[55%:60%]"
      test_split: "test[55%:60%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[60%:65%]"
      test_split: "test[60%:65%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[65%:70%]"
      test_split: "test[65%:70%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[70%:75%]"
      test_split: "test[70%:75%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[75%:80%]"
      test_split: "test[75%:80%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[80%:85%]"
      test_split: "test[80%:85%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[85%:90%]"
      test_split: "test[85%:90%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[90%:95%]"
      test_split: "test[90%:95%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsstore/rech/qts/ucg53vj/local-slim-lf
      train_split: "train[95%:100%]"
      test_split: "test[95%:100%]"
      build_test_set_from_train: false
      load_from_disk: true
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/gutenberg_canaries
      train_split: "train"
      build_test_set_from_train: true
      num_test_examples: 0

# tokenizer: "mistralai/Mistral-7B-v0.1"
tokenizer: "/gpfsstore/rech/qts/ucg53vj/tok-fr-en-code"
