data_mix:
  (): dataset_construction.DataMix
  name: "english_660B_13"
  shuffle: false
  load_from_local_save_dir: false
  local_save_dir: /gpfsscratch/rech/qts/ucg53vj/croissant_data
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: false
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  max_shard_size: "5GB"
  datasets:
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*0.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*1.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*2.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*3.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*4.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*5.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*6.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*7.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*8.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk4/*9.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*0.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*1.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*2.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*3.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*4.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*5.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*6.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*7.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*8.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk5/*9.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter

# tokenizer: "mistralai/Mistral-7B-v0.1"
tokenizer: "/gpfsstore/rech/qts/ucg53vj/tok-fr-en-code"
