data_mix:
  (): dataset_construction.DataMix
  name: "english_660B_11"
  shuffle: false
  load_from_local_save_dir: false
  local_save_dir: /gpfsscratch/rech/qts/ucg53vj/croissant_data
  compute_dataset_stats: true
  keep_separated_datasets_in_dataset_dict: false
  deduplicate_test_set: false
  ngram_path_for_extra_deduplication: null
  max_shard_size: "5GB"
  datasets:
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/gutenberg_canaries
      train_split: "train"
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/pg19
      preprocessing_function:
        (): dataset_collection.english.pg19.PG19Mapper
      train_split: "train"
      test_split: "test"
      build_test_set_from_train: false
    # Split of SlimPajama
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*0.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*1.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*2.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*3.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*4.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*5.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*6.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*7.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*8.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter
    - (): dataset_construction.DatasetConfig
      dataset_path: /gpfsscratch/rech/qts/ucg53vj/SlimPajama-627B
      train_split: "train"
      load_from_disk: false
      dataset_kwargs:
        data_files: train/chunk1/*9.jsonl.zst
      preprocessing_function:
        (): dataset_collection.english.slimpajama.SlimPajamaMapper
      filtering_function:
        (): dataset_collection.english.slimpajama.SlimPajamaFilter

# tokenizer: "mistralai/Mistral-7B-v0.1"
tokenizer: "/gpfsstore/rech/qts/ucg53vj/tok-fr-en-code"
